/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package renardo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CalculationTest {

    @Test void simpleAddition() {
        Calculation calculation = new Calculation(1,1);
        Result result = calculation.add();
        assertEquals(new Result(2,calculation),result);
    }

    
    @Test void simpleSubstraction() {
        Calculation calculation = new Calculation(1,1);
        Result result = calculation.substract();
        assertEquals(new Result(0,calculation),result);
    }

    
    @Test void simpleMultiplication() {
        Calculation calculation = new Calculation(2,2);
        Result result = calculation.multiply();
        assertEquals(new Result(4,calculation),result);
    }

    @Test void simpleDivision() {
        Calculation calculation = new Calculation(4,2);
        Result result = calculation.divide();
        assertEquals(new Result(2,calculation),result);
    }

}
