/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.nfl.renardo.calculation;

public class App {

	public static void main(String[] args) {
      Suite suite = Suite.from(7,2,8,4,25,6);
      final var now = System.currentTimeMillis();
      suite.calculate();
      System.out.println("Calculation took : "+(System.currentTimeMillis() - now)+"ms");
      //suite.showResults();
	}
}
